server:
  name: mysqlclient_test
  author: airing
  version: 1.0
  port:
  netTimeOutMs: 5000

log:
  level: debug
  path: ../log/
  maxSize: 100   #mb
  maxBackups: 20 #file count
  maxAge: 30     #days
  compress: true

mysql_test1:
  addr: "root:test.2020@tcp(127.0.0.1:3306)/air_test?charset=utf8"
  maxIdleConns: 30
  maxOpenConns: 300